### ISSUE TITLE
Launch is not created 405

### ISSUE THREAD

**Issue by donrifad** [reportportal/examples-js#37] opened 2022-12-15 21:46 UTC
I have checked out the code and provided 
1. Report portal deafult cloud configurations to update the report - Failing
2. Personal portals configurations - Failing

<img width="1072" alt="Screen Shot 2022-12-16 at 1 31 09 AM" src="https://user-images.githubusercontent.com/5151534/207971922-d7f4afef-9e0f-4361-8f0f-714a3af89db1.png">

Issue 2 no launch is created 

`module.exports = defineConfig({
  headless: true,
  reporter: '@reportportal/agent-js-cypress',
  reporterOptions: {
      endpoint: 'http://152.554.218.73:8082jj',
      token:
      launch: 'default_TEST_EXAMPLE',
      project: ,
      description: 'default_TEST_EXAMPLE',
  },
  e2e: {
    setupNodeEvents(on, config) {
      return registerReportPortalPlugin(on, config)
    },
  },
});
`
Could someone help I am I missing some thing?

**Comment by AmsterGet** [comment] 2023-01-16 08:59
Closed as a duplicate of https://github.com/reportportal/agent-js-cypress/issues/138

**Closed by AmsterGet** 2023-01-16 08:59 UTC
